/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MatchResult = {
    'matched' : { 'peerId' : UserId, 'sessionId' : SessionId }
  } |
  { 'waiting' : { 'position' : bigint } };
export type SessionId = string;
export type SessionStatus = { 'active' : { 'peerConnected' : boolean } } |
  { 'notFound' : null };
export interface SignalingEnvelope {
  'msg' : SignalingMsg,
  'from' : UserId,
  'sentAt' : Timestamp,
}
export type SignalingMsg = {
    'iceCandidate' : {
      'candidate' : string,
      'sdpMid' : [] | [string],
      'sdpMLineIndex' : [] | [bigint],
    }
  } |
  { 'offer' : { 'sdp' : string } } |
  { 'answer' : { 'sdp' : string } };
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'checkMatch' : ActorMethod<[], MatchResult>,
  'endSession' : ActorMethod<[SessionId], undefined>,
  'enterQueue' : ActorMethod<[], bigint>,
  'getSessionStatus' : ActorMethod<[SessionId], SessionStatus>,
  'leaveQueue' : ActorMethod<[], undefined>,
  'pollSignaling' : ActorMethod<[SessionId], Array<SignalingEnvelope>>,
  'sendAnswer' : ActorMethod<[SessionId, string], undefined>,
  'sendIceCandidate' : ActorMethod<
    [SessionId, string, [] | [string], [] | [bigint]],
    undefined
  >,
  'sendOffer' : ActorMethod<[SessionId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];