/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const SessionId = IDL.Text;
export const MatchResult = IDL.Variant({
  'matched' : IDL.Record({ 'peerId' : UserId, 'sessionId' : SessionId }),
  'waiting' : IDL.Record({ 'position' : IDL.Nat }),
});
export const SessionStatus = IDL.Variant({
  'active' : IDL.Record({ 'peerConnected' : IDL.Bool }),
  'notFound' : IDL.Null,
});
export const SignalingMsg = IDL.Variant({
  'iceCandidate' : IDL.Record({
    'candidate' : IDL.Text,
    'sdpMid' : IDL.Opt(IDL.Text),
    'sdpMLineIndex' : IDL.Opt(IDL.Nat),
  }),
  'offer' : IDL.Record({ 'sdp' : IDL.Text }),
  'answer' : IDL.Record({ 'sdp' : IDL.Text }),
});
export const Timestamp = IDL.Int;
export const SignalingEnvelope = IDL.Record({
  'msg' : SignalingMsg,
  'from' : UserId,
  'sentAt' : Timestamp,
});

export const idlService = IDL.Service({
  'checkMatch' : IDL.Func([], [MatchResult], []),
  'endSession' : IDL.Func([SessionId], [], []),
  'enterQueue' : IDL.Func([], [IDL.Nat], []),
  'getSessionStatus' : IDL.Func([SessionId], [SessionStatus], []),
  'leaveQueue' : IDL.Func([], [], []),
  'pollSignaling' : IDL.Func([SessionId], [IDL.Vec(SignalingEnvelope)], []),
  'sendAnswer' : IDL.Func([SessionId, IDL.Text], [], []),
  'sendIceCandidate' : IDL.Func(
      [SessionId, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'sendOffer' : IDL.Func([SessionId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const SessionId = IDL.Text;
  const MatchResult = IDL.Variant({
    'matched' : IDL.Record({ 'peerId' : UserId, 'sessionId' : SessionId }),
    'waiting' : IDL.Record({ 'position' : IDL.Nat }),
  });
  const SessionStatus = IDL.Variant({
    'active' : IDL.Record({ 'peerConnected' : IDL.Bool }),
    'notFound' : IDL.Null,
  });
  const SignalingMsg = IDL.Variant({
    'iceCandidate' : IDL.Record({
      'candidate' : IDL.Text,
      'sdpMid' : IDL.Opt(IDL.Text),
      'sdpMLineIndex' : IDL.Opt(IDL.Nat),
    }),
    'offer' : IDL.Record({ 'sdp' : IDL.Text }),
    'answer' : IDL.Record({ 'sdp' : IDL.Text }),
  });
  const Timestamp = IDL.Int;
  const SignalingEnvelope = IDL.Record({
    'msg' : SignalingMsg,
    'from' : UserId,
    'sentAt' : Timestamp,
  });
  
  return IDL.Service({
    'checkMatch' : IDL.Func([], [MatchResult], []),
    'endSession' : IDL.Func([SessionId], [], []),
    'enterQueue' : IDL.Func([], [IDL.Nat], []),
    'getSessionStatus' : IDL.Func([SessionId], [SessionStatus], []),
    'leaveQueue' : IDL.Func([], [], []),
    'pollSignaling' : IDL.Func([SessionId], [IDL.Vec(SignalingEnvelope)], []),
    'sendAnswer' : IDL.Func([SessionId, IDL.Text], [], []),
    'sendIceCandidate' : IDL.Func(
        [SessionId, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'sendOffer' : IDL.Func([SessionId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };