/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export type SignalingMsg = {
    __kind__: "iceCandidate";
    iceCandidate: {
        candidate: string;
        sdpMid?: string;
        sdpMLineIndex?: bigint;
    };
} | {
    __kind__: "offer";
    offer: {
        sdp: string;
    };
} | {
    __kind__: "answer";
    answer: {
        sdp: string;
    };
};
export type MatchResult = {
    __kind__: "matched";
    matched: {
        peerId: UserId;
        sessionId: SessionId;
    };
} | {
    __kind__: "waiting";
    waiting: {
        position: bigint;
    };
};
export type SessionStatus = {
    __kind__: "active";
    active: {
        peerConnected: boolean;
    };
} | {
    __kind__: "notFound";
    notFound: null;
};
export interface SignalingEnvelope {
    msg: SignalingMsg;
    from: UserId;
    sentAt: Timestamp;
}
export type SessionId = string;
export interface backendInterface {
    checkMatch(): Promise<MatchResult>;
    endSession(sessionId: SessionId): Promise<void>;
    enterQueue(): Promise<bigint>;
    getSessionStatus(sessionId: SessionId): Promise<SessionStatus>;
    leaveQueue(): Promise<void>;
    pollSignaling(sessionId: SessionId): Promise<Array<SignalingEnvelope>>;
    sendAnswer(sessionId: SessionId, sdp: string): Promise<void>;
    sendIceCandidate(sessionId: SessionId, candidate: string, sdpMid: string | null, sdpMLineIndex: bigint | null): Promise<void>;
    sendOffer(sessionId: SessionId, sdp: string): Promise<void>;
}
import type { MatchResult as _MatchResult, SessionId as _SessionId, SessionStatus as _SessionStatus, SignalingEnvelope as _SignalingEnvelope, SignalingMsg as _SignalingMsg, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async checkMatch(): Promise<MatchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.checkMatch();
                return from_candid_MatchResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkMatch();
            return from_candid_MatchResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async endSession(arg0: SessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endSession(arg0);
            return result;
        }
    }
    async enterQueue(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.enterQueue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enterQueue();
            return result;
        }
    }
    async getSessionStatus(arg0: SessionId): Promise<SessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionStatus(arg0);
                return from_candid_SessionStatus_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionStatus(arg0);
            return from_candid_SessionStatus_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async leaveQueue(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveQueue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveQueue();
            return result;
        }
    }
    async pollSignaling(arg0: SessionId): Promise<Array<SignalingEnvelope>> {
        if (this.processError) {
            try {
                const result = await this.actor.pollSignaling(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pollSignaling(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendAnswer(arg0: SessionId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAnswer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAnswer(arg0, arg1);
            return result;
        }
    }
    async sendIceCandidate(arg0: SessionId, arg1: string, arg2: string | null, arg3: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendIceCandidate(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendIceCandidate(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async sendOffer(arg0: SessionId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendOffer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendOffer(arg0, arg1);
            return result;
        }
    }
}
function from_candid_MatchResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchResult): MatchResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_SignalingEnvelope_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalingEnvelope): SignalingEnvelope {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SignalingMsg_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalingMsg): SignalingMsg {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    candidate: string;
    sdpMid: [] | [string];
    sdpMLineIndex: [] | [bigint];
}): {
    candidate: string;
    sdpMid?: string;
    sdpMLineIndex?: bigint;
} {
    return {
        candidate: value.candidate,
        sdpMid: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.sdpMid)),
        sdpMLineIndex: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.sdpMLineIndex))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    msg: _SignalingMsg;
    from: _UserId;
    sentAt: _Timestamp;
}): {
    msg: SignalingMsg;
    from: UserId;
    sentAt: Timestamp;
} {
    return {
        msg: from_candid_SignalingMsg_n8(_uploadFile, _downloadFile, value.msg),
        from: value.from,
        sentAt: value.sentAt
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matched: {
        peerId: _UserId;
        sessionId: _SessionId;
    };
} | {
    waiting: {
        position: bigint;
    };
}): {
    __kind__: "matched";
    matched: {
        peerId: UserId;
        sessionId: SessionId;
    };
} | {
    __kind__: "waiting";
    waiting: {
        position: bigint;
    };
} {
    return "matched" in value ? {
        __kind__: "matched",
        matched: value.matched
    } : "waiting" in value ? {
        __kind__: "waiting",
        waiting: value.waiting
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: {
        peerConnected: boolean;
    };
} | {
    notFound: null;
}): {
    __kind__: "active";
    active: {
        peerConnected: boolean;
    };
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "active" in value ? {
        __kind__: "active",
        active: value.active
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    iceCandidate: {
        candidate: string;
        sdpMid: [] | [string];
        sdpMLineIndex: [] | [bigint];
    };
} | {
    offer: {
        sdp: string;
    };
} | {
    answer: {
        sdp: string;
    };
}): {
    __kind__: "iceCandidate";
    iceCandidate: {
        candidate: string;
        sdpMid?: string;
        sdpMLineIndex?: bigint;
    };
} | {
    __kind__: "offer";
    offer: {
        sdp: string;
    };
} | {
    __kind__: "answer";
    answer: {
        sdp: string;
    };
} {
    return "iceCandidate" in value ? {
        __kind__: "iceCandidate",
        iceCandidate: from_candid_record_n10(_uploadFile, _downloadFile, value.iceCandidate)
    } : "offer" in value ? {
        __kind__: "offer",
        offer: value.offer
    } : "answer" in value ? {
        __kind__: "answer",
        answer: value.answer
    } : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SignalingEnvelope>): Array<SignalingEnvelope> {
    return value.map((x)=>from_candid_SignalingEnvelope_n6(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
